# Default state for all rules
default: true

line-length: false

# MD033/no-inline-html - Inline HTML
MD033:
  # Allowed elements
  allowed_elements: ["style"]

# MD025/empty-line-between-blocks - Empty line between blocks
MD025: false
MD029: false
  